import dotenv from "dotenv";
dotenv.config({ path: ".env" });

import mongoose from "mongoose";
import connectDB from "../db/index.js";
import { Subject } from "../models/subjects.model.js";

// ─── All B.Tech CSE Subjects (Semester 1–8, IKGPTU Pattern) ──────
const allSubjects = [
  // ════════════════════ SEMESTER 1 ════════════════════
  {
    subjectTitle: "Engineering Mathematics-I",
    subjectCode: "BTAM101",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Engineering Physics",
    subjectCode: "BTPH101",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Programming in C",
    subjectCode: "BTCS101",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Communication Skills",
    subjectCode: "BTHU101",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Electrical Engineering",
    subjectCode: "BTEE101",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "C Programming Lab",
    subjectCode: "BTCS111",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Physics Lab",
    subjectCode: "BTPH111",
    type: "P",
    credits: 1,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Electrical Engineering Lab",
    subjectCode: "BTEE111",
    type: "P",
    credits: 1,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },

  // ════════════════════ SEMESTER 2 ════════════════════
  {
    subjectTitle: "Engineering Mathematics-II",
    subjectCode: "BTAM201",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Engineering Chemistry",
    subjectCode: "BTCH201",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Data Structures",
    subjectCode: "BTCS201",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Digital Electronics",
    subjectCode: "BTEC201",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Environmental Studies",
    subjectCode: "BTHU201",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Data Structures Lab",
    subjectCode: "BTCS211",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Chemistry Lab",
    subjectCode: "BTCH211",
    type: "P",
    credits: 1,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Engineering Graphics Lab",
    subjectCode: "BTME211",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },

  // ════════════════════ SEMESTER 3 ════════════════════
  {
    subjectTitle: "Discrete Mathematics",
    subjectCode: "BTAM301",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Object Oriented Programming",
    subjectCode: "BTCS301",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Computer Organization & Architecture",
    subjectCode: "BTCS302",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Database Management Systems",
    subjectCode: "BTCS303",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Economics for Engineers",
    subjectCode: "BTHU301",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "OOP Lab (Java/C++)",
    subjectCode: "BTCS311",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "DBMS Lab",
    subjectCode: "BTCS312",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },

  // ════════════════════ SEMESTER 4 ════════════════════
  {
    subjectTitle: "Operating Systems",
    subjectCode: "BTCS401",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Design & Analysis of Algorithms",
    subjectCode: "BTCS402",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Software Engineering",
    subjectCode: "BTCS403",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Theory of Computation",
    subjectCode: "BTCS404",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Probability & Statistics",
    subjectCode: "BTAM401",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "OS Lab",
    subjectCode: "BTCS411",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Algorithms Lab",
    subjectCode: "BTCS412",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },

  // ════════════════════ SEMESTER 5 ════════════════════
  {
    subjectTitle: "Computer Networks",
    subjectCode: "BTCS501",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Compiler Design",
    subjectCode: "BTCS502",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Microprocessors & Interfacing",
    subjectCode: "BTCS503",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Web Technologies",
    subjectCode: "BTCS504",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Management & Entrepreneurship",
    subjectCode: "BTHU501",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Computer Networks Lab",
    subjectCode: "BTCS511",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Web Technologies Lab",
    subjectCode: "BTCS512",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },

  // ════════════════════ SEMESTER 6 ════════════════════
  {
    subjectTitle: "Artificial Intelligence",
    subjectCode: "BTCS601",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Machine Learning",
    subjectCode: "BTCS602",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Information Security",
    subjectCode: "BTCS603",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Cloud Computing",
    subjectCode: "BTCS604",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Professional Ethics",
    subjectCode: "BTHU601",
    type: "T",
    credits: 2,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "AI & ML Lab",
    subjectCode: "BTCS611",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Minor Project",
    subjectCode: "BTCS612",
    type: "P",
    credits: 4,
    maxInternalMarks: 60,
    maxExternalMarks: 40,
    maxTotalMarks: 100,
    minInternalPassMarks: 24,
    minExternalPassMarks: 16,
    minTotalPassMarks: 50,
  },

  // ════════════════════ SEMESTER 7 ════════════════════
  {
    subjectTitle: "Deep Learning",
    subjectCode: "BTCS701",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Big Data Analytics",
    subjectCode: "BTCS702",
    type: "T",
    credits: 4,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Internet of Things",
    subjectCode: "BTCS703",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Elective I: Natural Language Processing",
    subjectCode: "BTCS704",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Deep Learning Lab",
    subjectCode: "BTCS711",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
  {
    subjectTitle: "Major Project Phase-I",
    subjectCode: "BTCS712",
    type: "P",
    credits: 4,
    maxInternalMarks: 60,
    maxExternalMarks: 40,
    maxTotalMarks: 100,
    minInternalPassMarks: 24,
    minExternalPassMarks: 16,
    minTotalPassMarks: 50,
  },

  // ════════════════════ SEMESTER 8 ════════════════════
  {
    subjectTitle: "Blockchain Technology",
    subjectCode: "BTCS801",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Elective II: Computer Vision",
    subjectCode: "BTCS802",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Elective III: Quantum Computing",
    subjectCode: "BTCS803",
    type: "T",
    credits: 3,
    maxInternalMarks: 40,
    maxExternalMarks: 60,
    maxTotalMarks: 100,
    minInternalPassMarks: 16,
    minExternalPassMarks: 24,
    minTotalPassMarks: 40,
  },
  {
    subjectTitle: "Major Project Phase-II",
    subjectCode: "BTCS811",
    type: "P",
    credits: 8,
    maxInternalMarks: 60,
    maxExternalMarks: 40,
    maxTotalMarks: 100,
    minInternalPassMarks: 24,
    minExternalPassMarks: 16,
    minTotalPassMarks: 50,
  },
  {
    subjectTitle: "Seminar & Technical Writing",
    subjectCode: "BTCS812",
    type: "P",
    credits: 2,
    maxInternalMarks: 30,
    maxExternalMarks: 20,
    maxTotalMarks: 50,
    minInternalPassMarks: 12,
    minExternalPassMarks: 8,
    minTotalPassMarks: 25,
  },
];

// ─── Seed Function ───────────────────────────────────────────────
const seedSubjects = async () => {
  try {
    await connectDB();
    console.log("\n📚 Starting Subject Seed...\n");

    // Clear existing subjects
    const deleted = await Subject.deleteMany({});
    console.log(`🗑️  Cleared ${deleted.deletedCount} existing subjects`);

    // Insert all subjects
    const docs = await Subject.insertMany(allSubjects);
    console.log(`✅ Inserted ${docs.length} subjects successfully\n`);

    // Print semester-wise summary
    const semesterMap = {};
    docs.forEach((doc) => {
      const semNum = doc.subjectCode.charAt(4); // e.g. BTCS'1'01 → sem 1
      if (!semesterMap[semNum]) semesterMap[semNum] = [];
      semesterMap[semNum].push(doc);
    });

    for (const [sem, subjects] of Object.entries(semesterMap).sort()) {
      const theory = subjects.filter((s) => s.type === "T").length;
      const practical = subjects.filter((s) => s.type === "P").length;
      const totalCredits = subjects.reduce((sum, s) => sum + s.credits, 0);
      console.log(
        `   Semester ${sem}: ${subjects.length} subjects (${theory}T + ${practical}P) → ${totalCredits} credits`,
      );
    }

    console.log(`\n📊 Total: ${docs.length} subjects across 8 semesters\n`);
  } catch (error) {
    console.error("❌ Subject seed failed:", error.message);
    if (error.writeErrors) {
      error.writeErrors.forEach((e) => console.error(`   → ${e.err.errmsg}`));
    }
  } finally {
    await mongoose.disconnect();
    console.log("📴 Disconnected from MongoDB\n");
  }
};

seedSubjects();
